# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='tasklist',
        ),
        migrations.RemoveField(
            model_name='share',
            name='username',
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
