# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner1', to=settings.AUTH_USER_MODEL),
        ),
    ]
