# Generated by Django 2.2.1 on 2019-05-31 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20170529_1326'),
        ('todolist', '0008_auto_20170517_2358'),
    ]

    operations = [
    ]
